name: Create Archive
on: 
 push:
  branches:
  - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@master
      with:
        submodules: true
    - name: Set Time
      env:
        TZ: 'Asia/Tokyo'
      run: echo "CURRENT_DATETIME=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV
    
    - run: echo "RELEASE_FILENAME=local_2bbb_addons.zip" >> $GITHUB_ENV
    - run: echo release on ${{ env.CURRENT_DATETIME }} > /home/runner/work/local_2bbb_addons/local_2bbb_addons/version
    - run: echo commit $(cd /home/runner/work/local_2bbb_addons/local_2bbb_addons && git log --format="%H" -n 1) >> /home/runner/work/local_2bbb_addons/local_2bbb_addons/version

    # - name: Delete nightly Release and Tag
    #   uses: dev-drprasad/delete-tag-and-release@v1.1
    #   with:
    #     tag_name: 'nightly'
    #     delete_release: true
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Archive Release
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: ${{ env.RELEASE_FILENAME }}
        exclusions: '*.git*'

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v0.1.15
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: nightly
        name: nightly
        draft: false
        prerelease: false
        files: ${{ env.RELEASE_FILENAME }}
